src/authenticate/urls.py
from django.urls import path, include
from . import views

app_name = 'authenticate'

urlpatterns = [
   path('', views.home, name='home'),
   path('login/', views.login_user, name='login'),
   path('logout/', views.logout_user, name='logout'),
   path('register/', views.register_user, name='register'),
   path('edit_profile', views.edit_profile, name='edit_profile'),
   path('change_password', views.change_password, name='change_password'),
]

src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.view, name='shoe_list'),
 
 
]

src/customerservice/urls.py
from django.urls import path
from . import views


app_name = 'customerservice'

urlpatterns = [
    path('', views.show, name='show'),
    path('pricing', views.pricing, name='pricing'),
    path('faq', views.faq, name='faq'),

]

src/shoe/urls.py
from django.urls import path
from . import views


app_name = 'shoe'

urlpatterns = [
    path('', views.shoe_list, name='shoe_list'),
    path('liked_list', views.liked_list, name="liked_list"),
    path('cart_list/<shoe_id>', views.cart_list, name="cart_list"),
   	path('gender_male', views.gender_male, name="gender_male"),
   	path('gender_female', views.gender_female, name="gender_female"),
   	path('s', views.search, name="search"),
   	path('sidebar', views.sidebar, name="sidebar"),
   	path('men_sneakers', views.men_sneakers, name="men_sneakers"),
   	path('men_business', views.men_business, name="men_business"),
   	path('men_casual', views.men_casual, name="men_casual"),
   	path('men_boots', views.men_boots, name="men_boots"),
   	path('men_sandals', views.men_sandals, name="men_sandals"),
   	path('women_sneakers', views.women_sneakers, name="women_sneakers"),
   	path('women_flats', views.women_flats, name="women_flats"),
   	path('women_pumps', views.women_pumps, name="women_pumps"),
   	path('women_boots', views.women_boots, name="women_boots"),
   	path('women_sandals', views.women_sandals, name="women_sandals"),
	path('new_arrivals', views.new_arrivals, name="new_arrivals"),
	path('like/<shoe_id>', views.like, name="like"),

]

src/templates/base.html
{% load static %}
{% load fontawesome %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <style>
      @import url("https://fonts.googleapis.com/css?family=Permanent+Marker");
      svg {
        max-width: 30rem;
        width: 100%;
        height: auto;
        fill: none;
        stroke: white;
        stroke-width: 8;
      }
      svg tspan > tspan {
        stroke-dasharray: 1500;
        stroke-dashoffset: -1500;
      }
      svg tspan > tspan:nth-of-type(1) {
        -webkit-animation: draw 300ms 150ms forwards;
        animation: draw 300ms 150ms forwards;
      }
      svg tspan > tspan:nth-of-type(2) {
        -webkit-animation: draw 300ms 300ms forwards;
        animation: draw 300ms 300ms forwards;
      }
      svg tspan > tspan:nth-of-type(3) {
        -webkit-animation: draw 300ms 450ms forwards;
        animation: draw 300ms 450ms forwards;
      }
      svg tspan > tspan:nth-of-type(4) {
        -webkit-animation: draw 300ms 600ms forwards;
        animation: draw 300ms 600ms forwards;
      }
      svg tspan > tspan:nth-of-type(5) {
        -webkit-animation: draw 300ms 750ms forwards;
        animation: draw 300ms 750ms forwards;
      }
      svg tspan > tspan:nth-of-type(6) {
        -webkit-animation: draw 300ms 900ms forwards;
        animation: draw 300ms 900ms forwards;
      }
      svg tspan > tspan:nth-of-type(7) {
        -webkit-animation: draw 300ms 1050ms forwards;
        animation: draw 300ms 1050ms forwards;
      }
      svg tspan > tspan:nth-of-type(8) {
        -webkit-animation: draw 300ms 1200ms forwards;
        animation: draw 300ms 1200ms forwards;
      }
      svg tspan > tspan:nth-of-type(9) {
        -webkit-animation: draw 300ms 1350ms forwards;
        animation: draw 300ms 1350ms forwards;
      }
      svg tspan > tspan:nth-of-type(10) {
        -webkit-animation: draw 300ms 1500ms forwards;
        animation: draw 300ms 1500ms forwards;
      }
      svg tspan > tspan:nth-of-type(11) {
        -webkit-animation: draw 300ms 1650ms forwards;
        animation: draw 300ms 1650ms forwards;
      }
      @-webkit-keyframes draw {
        100% {
          stroke-dashoffset: 0;
        }
      }

      @keyframes draw {
        100% {
          stroke-dashoffset: 0;
        }
      }
    </style>
  </head>
  <body>



  <section style="background-color: rgb(30,30,30);">
      <svg viewBox="0 0 1418 116" version="1.1" xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink">
        <title>PerfectPair</title>
        <g stroke="none" fill="none" fill-rule="evenodd" fill-opacity="0">
          <text id="@WebDesignerMag" stroke="#fff" fill="#645F5A" font-weight="normal"
            font-family="PermanentMarker-Regular, Permanent Marker" font-size="144">
            <tspan x="3" y="109">
              <!--
					-->
              <tspan>P</tspan>
              <!--
					-->
              <tspan>e</tspan>
              <!--
					-->
              <tspan>r</tspan>
              <!--
					-->
              <tspan>f</tspan>
              <!--
					-->
              <tspan>e</tspan>
              <!--
					-->
              <tspan>c</tspan>
              <!--
					-->
              <tspan>t</tspan>
              <!--
					-->
              <tspan>p</tspan>
              <!--
					-->
              <tspan>a</tspan>
              <!--
					-->
              <tspan>i</tspan>
              <!--
					-->
              <tspan>r</tspan>
            </tspan>
          </text>
        </g>
      </svg>
    <!-- <h1 class="d-inline bg-warning">Login/Logout</h1> -->
	</section>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      {% if user.is_authenticated %}
      <div class="con2" id="secondnav"> 
      {% else %}
      <div class="con1" id="secondnav">
      {% endif %}
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse con" id="navbakrNavDropdown">
            <ul class="navbar-nav">
              <li>
                <form  class="form-inline my-2 my-lg-0" action='/shoe/s'>
                    <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i
                        class="fas fa-search"></i> Search for Products</button>
                  </form>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}"><i class="fas fa-home fa-lg"></i> Home <span
                      class="sr-only"></span></a>
              </li>
              
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'shoe:new_arrivals' %}"><i
                    class="fas fa-prescription-bottle-alt fa-lg"></i> New Arrivals</a>
              </li>

              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-male fa-lg"></i> Men
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'shoe:men_sneakers' %}">Sneakers</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_business' %}">Business</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_casual' %}">Casual</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_boots' %}">Boots</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_sandals' %}">Sandals</a>
                </div>
              </li>

              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-female fa-lg"></i> Women
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'shoe:women_sneakers' %}">Sneakers</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_flats' %}">Flats</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_pumps' %}">Pumps</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_boots' %}">Boots</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_sandals' %}">Sandals</a>
                </div>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authenticate:logout' %}"> <i
                      class="fas fa-sign-out-alt fa-lg"></i> Logout</a>
                </li>
                <hr style="height:20px; width:1px; background-color:gray; margin-top: 10px;">

                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authenticate:edit_profile' %}"><i class="fas fa-user-edit fa-lg"></i> Edit
                    Profile</a>
                </li>
                <hr style="height:20px; width:1px; background-color:gray; margin-top: 10px;">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authenticate:change_password' %}">Change Password</a>
                </li>
              {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authenticate:login' %}"><i class="fas fa-sign-in-alt fa-lg"></i> Login</a>
                </li>
                <hr style="height:20px; width:1px; background-color:gray; margin-top: 10px;">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'authenticate:register' %}"><i
                      class="fas fa-registered fa-lg"></i> Register</a>
                </li>
              {% endif %}

              
              <li class="nav-item nav-align">
                <a class="fas fa-shopping-cart fa-lg" href="{% url 'shoe:cart_list' shoe_id=15 %}"></a>
              </li>
              <li class="nav-item nav-align">
                <a class="fas fa-user fa-lg" href="{% url 'shoe:cart_list' shoe_id=15 %}"></a>
              </li>
              <li class="nav-item nav-align">
                <a class="fas fa-heart fa-lg" href="{% url 'shoe:liked_list' %}"></a>
              </li> 
            </ul>
          </div>
      </div>
    </nav>

    <br/>
    <div class='container'>
      {% if messages %}
        {% for message in messages %}
          <div class='alert alert-warning alert-dismissable' role='alert'>
            <button class='close' data-dismiss='alert'>
               <small><sup>x</sup></small>
            </button>
            {{message}}
          </div>
        {% endfor %}
      {% endif%}

      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% block script_block %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/scroll.js' %}"></script>
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% endblock %}
  </body>
</html>

src/templates/footer.html
  <style>
    .page-footer {
      background-color: #1C1C1C !important;
      color: white;
      font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
    }
    .mt-3{
      padding-top: 4%;
      margin-top: -1rem!important; 
    }
    .hr-color{
      background-color: white;
      width: 60px;
    }
     .py-3{
      padding-top: -1rem !important;
    }

  </style>
<div class="footer-copyright text-center py-3">Follow Us
      
 </div>

 <div class="container">
      <i class="fab fa-instagram fa-lg"></i>
      <i class="fab fa-twitter fa-lg"></i>
      <i class="fab fa-linkedin fa-lg"></i>
 </div>
<!-- Footer -->
<footer class="page-footer font-small unique-color-dark">

    

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

      <!-- Grid row -->
      <div class="row mt-3">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">Perfect Pair</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto hr-color" style="width: 60px;">
          <p>We are the number one ecommerce company for shoes. Massive selection, fast delivery, great customer service, and more</p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Shoes</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto hr-color" style="width: 60px;">
          <p>
            <a href="{% url 'shoe:gender_male' %}">Mens</a>

          </p>
          <p>
            <a href="{% url 'shoe:gender_female' %}">Womens</a>
          </p>
        

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Useful links</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto hr-color">
          <p>
            <a href="#!">Your Account</a>
          </p>
          <p>
            <a href="{% url 'customerservice:show' %}">Customer Service</a>
          </p>
          <p>
            <a href="{% url 'customerservice:pricing' %}">Shipping Rates</a>
          </p>
          <p>
            <a href="{% url 'customerservice:faq' %}">FAQ</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Contact</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto hr-color">
          <p>
            <i class="fas fa-home mr-3"></i>Miami, FL, US</p>
          <p>
            <i class="fas fa-envelope mr-3"></i>info@perfectpair.com</p>
          <p>
            <i class="fas fa-phone mr-3"></i>305 567 9488</p>
         
       


        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href=""> PerfectPair</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer --> 

src/templates/header.html
{% include "base.html" %}

{% load static %}



<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">


     
  
        <a  class="navbar-brand">Perfect Pair</a>
  

        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="header1">
          




          <li class="nav-item">
            <a id="z1" class="nav-link" href="{% url 'shoe:cart_list' %}" tabindex="-1">Login/Logout</a>
          </li>
        </ul>
      </div>
    </nav>

  


  
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container" id="secondnav">  
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li>
                  <form class="form-inline my-2 my-lg-0" action='/shoe/s'>
                    <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search for Products</button>
                  </form>
              </li>


              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shoe:new_arrivals' %}">New Arrivals</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact Us</a>
              </li>





  
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Men
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'shoe:men_sneakers' %}">Sneakers</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_business' %}">Business</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_casual' %}">Casual</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_boots' %}">Boots</a>
                  <a class="dropdown-item" href="{% url 'shoe:men_sandals' %}">Sandals</a>
                </div>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Women
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'shoe:women_sneakers' %}">Sneakers</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_flats' %}">Flats</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_pumps' %}">Pumps</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_boots' %}">Boots</a>
                  <a class="dropdown-item" href="{% url 'shoe:women_sandals' %}">Sandals</a>
                </div>
              </li>




              <li class="nav-item">
                <a class="fas fa-shopping-cart fa-lg" href="{% url 'shoe:cart_list' %}"></a>
              </li>
              <li class="nav-item">
                <a class="fas fa-user fa-lg" href="{% url 'shoe:cart_list' %}"></a>
              </li>
              <li class="nav-item">
                <a class="fas fa-heart fa-lg" href="{% url 'shoe:cart_list' %}"></a>
              </li>




            </ul>
          </div>
      </div>
    </nav>





    <h2>fdsfsdf</h2>

src/templates/home.html
{% include "base.html" %}
{% load static %}

{% block content %}

<style>
	
	.d-block{
		height: 100%;
	}
	.carousel-inner{
		height: 100%;
	}
	.carousel-item{
		height: 100%;
	}
	.mouse {
		max-width: 2.5rem;
		width: 100%;
		height: auto;
	}

	.scroll {
		-webkit-animation-name: scroll;
		animation-name: scroll;
		-webkit-animation-duration: 1.5s;
		animation-duration: 1.5s;
		-webkit-animation-timing-function: cubic-bezier(0.65, -0.55, 0.25, 1.5);
		animation-timing-function: cubic-bezier(0.65, -0.55, 0.25, 1.5);
		-webkit-animation-iteration-count: infinite;
		animation-iteration-count: infinite;
		-webkit-transform-origin: 50% 20.5px;
		transform-origin: 50% 20.5px;
		will-change: transform, opacity;
		opacity: 1;
	}

	.scroll-link {
		position: absolute;
		bottom: 1rem;
		left: 50%;
		-webkit-transform: translateX(-50%);
		transform: translateX(-50%);
	}

	@-webkit-keyframes scroll {
		0%, 20% {
			-webkit-transform: translateY(0) scaleY(1);
			transform: translateY(0) scaleY(1);
		}
		100% {
			-webkit-transform: translateY(36px) scaleY(2);
			transform: translateY(36px) scaleY(2);
			opacity: 0;
			}
	}

	@keyframes scroll {
		0%, 20% {
			-webkit-transform: translateY(0) scaleY(1);
			transform: translateY(0) scaleY(1);
		}
		100% {
			-webkit-transform: translateY(36px) scaleY(2);
			transform: translateY(36px) scaleY(2);
			opacity: 0;
		}
	}
</style>
<link href="{% static 'css/test.css' %}" rel="stylesheet">


	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
	  <div class="carousel-inner">
	    <div class="carousel-item active" id="zz">
				<img src="/media/shoe/s1.jpg" class="d-block w-100" alt="...">
			</div>
	    <div class="carousel-item">
	      <img src="/media/shoe/s2.jpg" class="d-block w-100" alt="...">
	    </div>
	    <div class="carousel-item">
	      <img src="/media/shoe/s3.jpg" class="d-block w-100" alt="...">
			</div>
			<a class="scroll-link" href="#section1">
				<svg class="mouse" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 76 130" preserveAspectRatio="xMidYMid meet">
					<g fill="none" fill-rule="evenodd">
						<rect width="70" height="118" x="1.5" y="1.5" stroke="#FFF" stroke-width="3" rx="36" />
						<circle class="scroll" cx="36.5" cy="31.5" r="4.5" fill="#FFF" />
					</g>
				</svg>
			</a>
		</div>
	  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
		</a>
	</div>	

	<section id="section1">
		<h1 class="d-inline bg-success">This is a </h1>
    <h1 class="d-inline bg-success">SECTION</h1>
	</section>

	<section>
		<h1 class="d-inline bg-warning">This is another </h1>
    <h1 class="d-inline bg-warning">SECTION</h1>
	</section>

	<section>
		<h1 class="d-inline bg-alert">This is should be the last </h1>
    <h1 class="d-inline bg-alert">SECTION</h1>
	</section>
{% include 'footer.html' %}
{% endblock content %}