src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.view, name='shoe_list'),
 
 
]

src/shoe/urls.py
from django.urls import path
from . import views


app_name = 'shoe'

urlpatterns = [
    path('', views.shoe_list, name='shoe_list'),
    path('liked_list', views.liked_list, name="liked_list"),
    path('cart_list/<shoe_id>', views.cart_list, name="cart_list"),
   	path('gender_male', views.gender_male, name="gender_male"),
   	path('gender_female', views.gender_female, name="gender_female"),
   	path('s', views.search, name="search"),
   	path('sidebar', views.sidebar, name="sidebar"),
   	path('men_sneakers', views.men_sneakers, name="men_sneakers"),
   	path('men_business', views.men_business, name="men_business"),
   	path('men_casual', views.men_casual, name="men_casual"),
   	path('men_boots', views.men_boots, name="men_boots"),
   	path('men_sandals', views.men_sandals, name="men_sandals"),
   	path('women_sneakers', views.women_sneakers, name="women_sneakers"),
   	path('women_flats', views.women_flats, name="women_flats"),
   	path('women_pumps', views.women_pumps, name="women_pumps"),
   	path('women_boots', views.women_boots, name="women_boots"),
   	path('women_sandals', views.women_sandals, name="women_sandals"),
	path('new_arrivals', views.new_arrivals, name="new_arrivals"),
	path('like/<shoe_id>', views.like, name="like"),

]

src/shoe/models.py
from django.db import models
import datetime

# Create your models here.


class Shoe(models.Model):
	name 			= models.CharField(max_length=30, default="Boosts")
	image 			= models.ImageField(upload_to='shoe/', blank=True, null=True)
	style 			= models.CharField(max_length=20, default="sneakers")
	size 			= models.IntegerField(default=10)
	color 			= models.CharField(max_length=20, default="blue")
	brand 			= models.CharField(max_length=20, default="Nike")
	price 			= models.DecimalField(max_digits=4, decimal_places=2, default=4.00)
	availability 	= models.BooleanField(default=True)
	new 			= models.BooleanField(default=True)
	stock 			= models.IntegerField(default=5)
	gender_choices 	= (
        ('M', 'Male'),
        ('F', 'Female'),
    )
	gender 			= models.CharField(max_length=1, choices=gender_choices, default="M")
	date 			= models.DateField(("Date"), default=datetime.date.today)
	like 			= models.BooleanField(default=False)




	def __str__(self):
		return str(self.name)

src/shoe/views.py
from django.db.models import Q
from .models import Shoe
from cart.models import Cart
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
# Create your views here.


def shoe_list(request):

	shoe_list = Shoe.objects.all()

	context = {

		'shoe_list': shoe_list,
	}

	return render(request, 'shoe/shoe_list.html', context)


def liked_list(request):

	shoe_list = Shoe.objects.filter(like=True)

	context = {
		'shoe_list': shoe_list,
	}

	return render(request, 'shoe/liked_list.html', context)


def cart_list(request, shoe_id):

	system = request.POST.get('cart', None)
	delete = request.GET.get('q1')
	print(delete)
	shoe = get_object_or_404(Shoe, pk=shoe_id)
	cart = Cart.objects.get(pk=2)
	shoe_list = []
	if delete=="delete":
		cart.products.remove(shoe)
		for shoe in cart.products.all():
			shoe_list.append(shoe)
		context = {
			'shoe_list': shoe_list,
			'system': system,
		}
		return render(request, 'shoe/cart_list.html', context)
	else:
		cart.products.add(shoe)
		cart.save()
		for shoe in cart.products.all():
			shoe_list.append(shoe)
		
		# shoe_list = Shoe.objects.all()
		context = {
			'shoe_list': shoe_list,
			'system': system,
		}

		return render(request, 'shoe/cart_list.html', context)



def gender_male(request):


	shoe_list = Shoe.objects.all()

	context = {

		'shoe_list': shoe_list,
	}

	return render(request, 'shoe/gender_male.html', context)


def gender_female(request):

	shoe_list = Shoe.objects.all()

	context = {

		'shoe_list': shoe_list,
	}

	return render(request, 'shoe/gender_female.html', context)


def search(request):
	
	q = request.GET.get('q')

	if q:
		products = Shoe.objects.filter(brand__icontains=q)	
		context = {'query': q, 'products': products}
		template = 'shoe/gender_male.html'

	elif q == '':
		template = 'home.html'
		context = {}
	else:
		template = 'home.html'
		context = {}
	return render(request, template, context)

def add_to_cart(request, shoe_id):
	shoe = get_object_or_404(Shoe, pk=shoe_id)

	context = {"shoe":shoe}

	return render(request, template, context)

def sidebar(request):
	q1 = request.GET.get('Adidas')
	q2 = request.GET.get('Nike')
	q3 = request.GET.get('Puma')
	f1 = "Adidas" if q1 == "on" else "1"
	f2 = "Nike" if q2 == "on" else "1"
	f3 = "Puma" if q3 == "on" else "1"
	q4 = request.GET.get('s10')
	q5 = request.GET.get('s9')
	q6 = request.GET.get('s8')
	f4 = 10 if q4 == "on" else 0
	f5 = 9 if q5 == "on" else 0
	f6 = 8 if q6 == "on" else 0
	q7 = request.GET.get('blue')
	q8 = request.GET.get('black')
	q9 = request.GET.get('red')
	f7 = "blue" if q7 == "on" else "1"
	f8 = "black" if q8 == "on" else "1"
	f9 = "red" if q9 == "on" else "1"
	q10 = request.GET.get('d10')
	q11 = request.GET.get('d9')
	q12 = request.GET.get('d8')
	f10 = 10 if q10 == "on" else 0
	f11 = 9 if q11 == "on" else 0
	f12 = 8 if q12 == "on" else 0

	products1 = Shoe.objects.filter(Q(brand__icontains=f1)|Q(brand__icontains=f2)|Q(brand__icontains=f3))
	products2 = Shoe.objects.filter(Q(size__exact=f4)|Q(size__exact=f5)|Q(size__exact=f6))
	products3 = Shoe.objects.filter(Q(color__icontains=f7)|Q(color__icontains=f8)|Q(color__icontains=f9))
	products4 = Shoe.objects.filter(Q(price__exact=f10)|Q(price__exact=f11)|Q(price__exact=f12))
	products = Shoe.objects.all()

	if(products1):
		products = products & products1
	if(products2):
		products = products & products2
	if(products3):
		products = products & products3
	if(products4):
		products = products & products4

	context = {'products': products}
	template = 'shoe/sidebar.html'

		
	return render(request, template, context)


def men_sneakers(request):
    	
	system = request.POST.get('cart', None)
	q1 = request.GET.get('Adidas')
	q2 = request.GET.get('Nike')
	q3 = request.GET.get('Puma')
	f1 = "Adidas" if q1 == "on" else "1"
	f2 = "Nike" if q2 == "on" else "1"
	f3 = "Puma" if q3 == "on" else "1"
	q4 = request.GET.get('s10')
	q5 = request.GET.get('s9')
	q6 = request.GET.get('s8')
	f4 = 10 if q4 == "on" else 0
	f5 = 9 if q5 == "on" else 0
	f6 = 8 if q6 == "on" else 0
	q7 = request.GET.get('blue')
	q8 = request.GET.get('black')
	q9 = request.GET.get('red')
	f7 = "blue" if q7 == "on" else "1"
	f8 = "black" if q8 == "on" else "1"
	f9 = "red" if q9 == "on" else "1"
	q10 = request.GET.get('d10')
	q11 = request.GET.get('d9')
	q12 = request.GET.get('d8')
	f10 = 10 if q10 == "on" else 0
	f11 = 9 if q11 == "on" else 0
	f12 = 8 if q12 == "on" else 0
	q13 = request.GET.get('All')

	shoe_list = Shoe.objects.filter(style="sneakers").filter(gender="M")
	products1 = Shoe.objects.filter(Q(brand__icontains=f1)|Q(brand__icontains=f2)|Q(brand__icontains=f3))
	products2 = Shoe.objects.filter(Q(size__exact=f4)|Q(size__exact=f5)|Q(size__exact=f6))
	products3 = Shoe.objects.filter(Q(color__icontains=f7)|Q(color__icontains=f8)|Q(color__icontains=f9))
	products4 = Shoe.objects.filter(Q(price__exact=f10)|Q(price__exact=f11)|Q(price__exact=f12))
	if products1.count()!=0:
		shoe_list = shoe_list & products1
	if products2.count()!=0:
		shoe_list = shoe_list & products2
	if products3.count()!=0:
		shoe_list = shoe_list & products3
	if products4.count()!=0:
		shoe_list = shoe_list & products4
	if ((products1.count(), products2.count(), products3.count(), products4.count())==(0,0,0,0)):
		shoe_list = []
		if q13=="on":
			shoe_list = Shoe.objects.filter(style="sneakers").filter(gender="M")

	context = {
		'shoe_list': shoe_list, }

	template = 'shoe/men_sneakers.html'
	
	return render(request, template, context)


def men_business(request):
    	
	system = request.POST.get('cart', None)
	q1 = request.GET.get('Adidas')
	q2 = request.GET.get('Nike')
	q3 = request.GET.get('Puma')
	f1 = "Adidas" if q1 == "on" else "1"
	f2 = "Nike" if q2 == "on" else "1"
	f3 = "Puma" if q3 == "on" else "1"
	q4 = request.GET.get('s10')
	q5 = request.GET.get('s9')
	q6 = request.GET.get('s8')
	f4 = 10 if q4 == "on" else 0
	f5 = 9 if q5 == "on" else 0
	f6 = 8 if q6 == "on" else 0
	q7 = request.GET.get('blue')
	q8 = request.GET.get('black')
	q9 = request.GET.get('red')
	f7 = "blue" if q7 == "on" else "1"
	f8 = "black" if q8 == "on" else "1"
	f9 = "red" if q9 == "on" else "1"
	q10 = request.GET.get('d10')
	q11 = request.GET.get('d9')
	q12 = request.GET.get('d8')
	f10 = 10 if q10 == "on" else 0
	f11 = 9 if q11 == "on" else 0
	f12 = 8 if q12 == "on" else 0
	q13 = request.GET.get('All')

	shoe_list = Shoe.objects.filter(style="business").filter(gender="M")
	products1 = Shoe.objects.filter(Q(brand__icontains=f1)|Q(brand__icontains=f2)|Q(brand__icontains=f3))
	products2 = Shoe.objects.filter(Q(size__exact=f4)|Q(size__exact=f5)|Q(size__exact=f6))
	products3 = Shoe.objects.filter(Q(color__icontains=f7)|Q(color__icontains=f8)|Q(color__icontains=f9))
	products4 = Shoe.objects.filter(Q(price__exact=f10)|Q(price__exact=f11)|Q(price__exact=f12))
	if products1.count()!=0:
		shoe_list = shoe_list & products1
	if products2.count()!=0:
		shoe_list = shoe_list & products2
	if products3.count()!=0:
		shoe_list = shoe_list & products3
	if products4.count()!=0:
		shoe_list = shoe_list & products4
	if ((products1.count(), products2.count(), products3.count(), products4.count())==(0,0,0,0)):
		shoe_list = []
		if q13=="on":
			shoe_list = Shoe.objects.filter(style="business").filter(gender="M")

	context = {

		'shoe_list': shoe_list,
	}

	template = 'shoe/men_business.html'
	

	return render(request, template, context)


def men_casual(request):
    	
	system = request.POST.get('cart', None)
	q1 = request.GET.get('Adidas')
	q2 = request.GET.get('Nike')
	q3 = request.GET.get('Puma')
	f1 = "Adidas" if q1 == "on" else "1"
	f2 = "Nike" if q2 == "on" else "1"
	f3 = "Puma" if q3 == "on" else "1"
	q4 = request.GET.get('s10')
	q5 = request.GET.get('s9')
	q6 = request.GET.get('s8')
	f4 = 10 if q4 == "on" else 0
	f5 = 9 if q5 == "on" else 0
	f6 = 8 if q6 == "on" else 0
	q7 = request.GET.get('blue')
	q8 = request.GET.get('black')
	q9 = request.GET.get('red')
	f7 = "blue" if q7 == "on" else "1"
	f8 = "black" if q8 == "on" else "1"
	f9 = "red" if q9 == "on" else "1"
	q10 = request.GET.get('d10')
	q11 = request.GET.get('d9')
	q12 = request.GET.get('d8')
	f10 = 10 if q10 == "on" else 0
	f11 = 9 if q11 == "on" else 0
	f12 = 8 if q12 == "on" else 0
	q13 = request.GET.get('All')

	shoe_list = Shoe.objects.filter(style="casual").filter(gender="M")
	products1 = Shoe.objects.filter(Q(brand__icontains=f1)|Q(brand__icontains=f2)|Q(brand__icontains=f3))
	products2 = Shoe.objects.filter(Q(size__exact=f4)|Q(size__exact=f5)|Q(size__exact=f6))
	products3 = Shoe.objects.filter(Q(color__icontains=f7)|Q(color__icontains=f8)|Q(color__icontains=f9))
	products4 = Shoe.objects.filter(Q(price__exact=f10)|Q(price__exact=f11)|Q(price__exact=f12))
	if products1.count()!=0:
		shoe_list = shoe_list & products1
	if products2.count()!=0:
		shoe_list = shoe_list & products2
	if products3.count()!=0:
		shoe_list = shoe_list & products3
	if products4.count()!=0:
		shoe_list = shoe_list & products4
	if ((products1.count(), products2.count(), products3.count(), products4.count())==(0,0,0,0)):
		shoe_list = []
		if q13=="on":
			shoe_list = Shoe.objects.filter(style="casual").filter(gender="M")


	context = {

		'shoe_list': shoe_list,
	}

	template = 'shoe/men_casual.html'
	

	return render(request, template, context)


def men_boots(request):
    	
	system = request.POST.get('cart', None)
	q1 = request.GET.get('Adidas')
	q2 = request.GET.get('Nike')
	q3 = request.GET.get('Puma')
	f1 = "Adidas" if q1 == "on" else "1"
	f2 = "Nike" if q2 == "on" else "1"
	f3 = "Puma" if q3 == "on" else "1"
	q4 = request.GET.get('s10')
	q5 = request.GET.get('s9')
	q6 = request.GET.get('s8')
	f4 = 10 if q4 == "on" else 0
	f5 = 9 if q5 == "on" else 0
	f6 = 8 if q6 == "on" else 0
	q7 = request.GET.get('blue')
	q8 = request.GET.get('black')
	q9 = request.GET.get('red')
	f7 = "blue" if q7 == "on" else "1"
	f8 = "black" if q8 == "on" else "1"
	f9 = "red" if q9 == "on" else "1"
	q10 = request.GET.get('d10')
	q11 = request.GET.get('d9')

src/shoe/templates/shoe/cart_list.html
{% include "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <div class='text-center'>
        <h1 class="title">Cart</h1>
    </div>
    <style>
    .title {
        font-family: 'American Typewriter', serif;
        text-align: center
    }
    </style>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Type</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Price</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for shoe in shoe_list %}
        <tr>
        <th scope="row">1</th>
        <td>{{ system }}</td>
        <td>{{shoe.name}}</td>
        <td>{{shoe.stock}}</td>
        <td>{{shoe.price}}</td>
        <td>
            <form action=" {% url 'shoe:cart_list' shoe_id=shoe.pk %}" id="delete">
                <input type="submit" class="btn btn-primary" style="background-color:red; border-color: red;" id="q1" name='q1' value="delete">
                </input>
            </form>
        </td>
        </tr>
    {% endfor %}

    </tbody>
    </table>

<h1>{{ system }}</h1>

{% endblock %}

src/shoe/templates/shoe/men_boots.html
{% include "base.html" %}
{% load static %}
{% block content %}

<style>
    @import url("https://fonts.googleapis.com/css?family=Lobster+Two");

    h1 {
        font-family: 'American Typewriter', serif;
        font-size: 3rem;
        text-shadow: 0px 1px 0px white;
        color: #343434;
    }

    .pulse {
        z-index: -1;
        position: absolute;
        top: 50%;
        left: 50%;
        -webkit-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        max-width: 30rem;
    }

    .pulse circle {
        fill: #ff5154;
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 0;
        -webkit-transform-origin: 50% 50%;
        transform-origin: 50% 50%;
        -webkit-animation: pulse 2s cubic-bezier(0.5, 0.5, 0, 1);
        animation: pulse 2s cubic-bezier(0.5, 0.5, 0, 1);
    }

    .pulse circle:nth-child(2) {
        fill: #7fc6a4;
        -webkit-animation: pulse 2s 0.75s cubic-bezier(0.5, 0.5, 0, 1);
        animation: pulse 2s 0.75s cubic-bezier(0.5, 0.5, 0, 1);
    }

    .pulse circle:nth-child(3) {
        fill: #e5f77d;
        -webkit-animation: pulse 2s 1.5s cubic-bezier(0.5, 0.5, 0, 1);
        animation: pulse 2s 1.5s cubic-bezier(0.5, 0.5, 0, 1);
    }

    @-webkit-keyframes pulse {
        25% {
            opacity: 0.4;
        }

        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
    }

    @keyframes pulse {
        25% {
            opacity: 0.4;
        }

        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
    }

    .title {
        font-family: 'American Typewriter', serif;
        text-align: center
    }

    .card-title {
        font-family: 'Comic sans MS', sans-serif;
        font-size: 23px;
    }

    .grid {
        display: grid;
        grid-template-columns: repeat(5, 1fr);
        grid-gap: 10px;
        grid-auto-rows: minmax(10px, auto);
    }

    .d-flex {
        background-color: rgb(238, 238, 238) !important;
    }

    .ele-text {
        font-family: 'American Typewriter', serif;
    }

    .card {
        left: 10% !important;
    }

    .li {
        list-style: none !important;
    }

    #sidebar-wrapper {
        min-height: 20vh;
        margin-left: -15rem;
        -webkit-transition: margin .25s ease-out;
        -moz-transition: margin .25s ease-out;
        -o-transition: margin .25s ease-out;
        transition: margin .25s ease-out;
    }

    #sidebar-wrapper .sidebar-heading {
        padding: 0.875rem 1.25rem;
        font-size: 1.2rem;
    }

    #sidebar-wrapper .list-group {
        width: 15rem;
    }

    /* #page-content-wrapper {
        min-width: 100vw;
    } */

    #wrapper.toggled #sidebar-wrapper {
        margin-left: 0;
    }
</style>
<div style="position:relative;">
    <h1 class="title">Men Boots</h1>
    <button class="btn fas fa-bars fa-2x" id="menu-toggle" style="position:absolute; top:0;"></button>
</div>
<svg class="pulse" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <circle id="Oval" cx="512" cy="512" r="512"></circle>
    <circle id="Oval" cx="512" cy="512" r="512"></circle>
    <circle id="Oval" cx="512" cy="512" r="512"></circle>
</svg>
<div class="d-flex toggled" id="wrapper">

    <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading">Filter By</div>
        <div class="list-group list-group-flush">
            <form action='/shoe/men_boots' id="filter" autocomplete="off">
                <ul class="sub-menu dropdown" id="brand">
                    <li class="active li filter"><a href="#"><input type="checkbox" name="All" id="All">
                            All</a></li>
                </ul>

                <li class="li" data-toggle="collapse" data-target="#brand">
                    <a href="#" class="list-group-item list-group-item-action bg-light title">Brand</a>
                </li>

                <ul class="sub-menu dropdown" id="brand">
                    <li class="active li filter"><a href="#"><input type="checkbox" name="Adidas" id="Adidas">
                            ADIDAS</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="Nike" id="Nike"> NIKE</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="Puma" id="Puma"> PUMA</a></li>
                </ul>

                <li class="li" data-toggle="collapse" data-target="#size">
                    <a href="#" class="list-group-item list-group-item-action bg-light title">Size</a>
                </li>

                <ul class="sub-menu dropdown" id="size">
                    <li class="active li filter"><a href="#"><input type="checkbox" name="s10" id="s10"> Size 10</a>
                    </li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="s9" id="s9"> Size 9</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="s8" id="s8"> Size 8</a></li>
                </ul>

                <li class="li" data-toggle="collapse" data-target="#color">
                    <a href="#" class="list-group-item list-group-item-action bg-light title">Color</a>
                </li>

                <ul class="sub-menu dropdown" id="color">
                    <li class="active li filter"><a href="#"><input type="checkbox" name="blue" id="blue"> Blue</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="black" id="black"> Black</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="red" id="red"> Red</a></li>
                </ul>

                <li class="li" data-toggle="collapse" data-target="#price">
                    <a href="#" class="list-group-item list-group-item-action bg-light title">Price</a>
                </li>

                <ul class="sub-menu dropdown" id="price">
                    <li class="active li filter"><a href="#"><input type="checkbox" name="d10" id="d10"> $10</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="d9" id="d9"> $9</a></li>
                    <li class="li filter"><a href="#"><input type="checkbox" name="d8" id="d8"> $8</a></li>
                </ul>
                <!-- <ul class="sum-menu">
          <input class="btn btn-primary" type="submit" value="Filter">
        </ul> -->
            </form>
        </div>
    </div>
    <form id="filter">
        <div class='mr-2 grid'>
            {% for shoe in shoe_list %}
            <div class="mb-4 mt-4 card text-left" style="width:16rem;">
                <img src="{{shoe.image.url}}" class="card-img-top" style="width:254px; height:250px">

                <div class="card-body" class="shadow-lg p-3 mb-5 bg-white rounded">
                    <h5 class="card-title">{{shoe.name}}</h5>
                    <p class="card-text ele-text">
                        <span>Type:</span>
                        <span style="float:right;">{{shoe.style}}</span>
                    </p>
                    <p class="card-text ele-text">
                        <span>Size: </span>
                        <span style="float:right;">{{shoe.size}}</span>
                    </p>
                    <p class="card-text ele-text">
                        <span>Price:</span>
                        <span style="float:right;color:turquoise; font-size: 25px!important;">${{shoe.price}}</span>
                    </p>
                    <p class="card-text ele-text">
                        <span>Only</span>
                        <span style="float:right">{{shoe.stock}} available</span>
                    </p>
                    <p class="card-text ele-text">
                        <span>Available: </span>
                        <span style="float:right">{{shoe.availability}}</span>
                    </p>
                    <div>
                        <a href="{% url 'shoe:cart_list' shoe_id=shoe.pk %}" class="btn btn-primary"
                            style="background-color:turquoise; border-color: turquoise;" name='q1'>
                            <i class="fas fa-shopping-cart fa-lg"></i>
                            Add to cart</a>
                        <div style="float:right">
                            <input id="apto" type="checkbox" {% if shoe.like %} checked{% endif %}>
                            <label for="apto"><a href="{% url 'shoe:like' shoe_id=shoe.pk %}">Liked</a></label>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </form>
</div>
<script type="text/javascript">
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    $(document).ready(function () {
        $('#All').attr('checked', localStorage.getItem("#All") == 'true' ? true : false);
        $('#Adidas').attr('checked', localStorage.getItem("#Adidas") == 'true' ? true : false);
        $('#Nike').attr('checked', localStorage.getItem("#Nike") == 'true' ? true : false);
        $('#Puma').attr('checked', localStorage.getItem("#Puma") == 'true' ? true : false);

        $('#s10').attr('checked', localStorage.getItem("#s10") == 'true' ? true : false);
        $('#s9').attr('checked', localStorage.getItem("#s9") == 'true' ? true : false);
        $('#s8').attr('checked', localStorage.getItem("#s8") == 'true' ? true : false);

        $('#blue').attr('checked', localStorage.getItem("#blue") == 'true' ? true : false);
        $('#black').attr('checked', localStorage.getItem("#black") == 'true' ? true : false);
        $('#red').attr('checked', localStorage.getItem("#red") == 'true' ? true : false);

        $('#d10').attr('checked', localStorage.getItem("#d10") == 'true' ? true : false);
        $('#d9').attr('checked', localStorage.getItem("#d9") == 'true' ? true : false);
        $('#d8').attr('checked', localStorage.getItem("#d8") == 'true' ? true : false);
    });
    $("#All").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#All", true);
        } else {
            localStorage.setItem("#All", false);
        }
        $("#filter").submit();
    });

    $("#Adidas").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#Adidas", true);
        } else {
            localStorage.setItem("#Adidas", false);
        }

        $("#filter").submit();
    });
    $("#Nike").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#Nike", true);
        } else {
            localStorage.setItem("#Nike", false);
        }
        $("#filter").submit();
    });

    $("#Puma").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#Puma", true);
        } else {
            localStorage.setItem("#Puma", false);
        }
        $("#filter").submit();
    });

    $("#s10").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#s10", true);
        } else {
            localStorage.setItem("#s10", false);
        }
        $("#filter").submit();
    });
    $("#s9").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#s9", true);
        } else {
            localStorage.setItem("#s9", false);
        }
        $("#filter").submit();
    });
    $("#s8").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#s8", true);
        } else {
            localStorage.setItem("#s8", false);
        }
        $("#filter").submit();
    });

    $("#blue").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#blue", true);
        } else {
            localStorage.setItem("#blue", false);
        }
        $("#filter").submit();
    });
    $("#black").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#black", true);
        } else {
            localStorage.setItem("#black", false);
        }
        $("#filter").submit();
    });
    $("#red").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#red", true);
        } else {
            localStorage.setItem("#red", false);
        }
        $("#filter").submit();
    });

    $("#d10").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#d10", true);
        } else {
            localStorage.setItem("#d10", false);
        }
        $("#filter").submit();
    });

    $("#d9").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#d9", true);
        } else {
            localStorage.setItem("#d9", false);
        }
        $("#filter").submit();
    });

    $("#d8").click(function () {
        if ($(this).is(':checked')) {
            localStorage.setItem("#d8", true);
        } else {
            localStorage.setItem("#d8", false);
        }
        $("#filter").submit();
    });
</script>
{% include 'footer.html' %}

{% endblock %}